### ISSUE TITLE
Inconsistencies in samtool version used in tasks

### ISSUE THREAD

**Issue by jvhagey** [StaPH-B/titan#10]
In [task_consensus_call.wdl](https://github.com/StaPH-B/public_health_viral_genomics/blob/main/tasks/task_consensus_call.wdl):

- The task `primer_trim` uses container `staphb/ivar:1.3.1`, which contains samtools v1.12 and NO bwa
- The task `variant_call` and `consensus` uses container `staphb/ivar:1.2.2_artic20200528`, which contains samtools v1.9 and bwa v0.7.17-r1188

[task_assembly_metrics.wdl](https://github.com/StaPH-B/public_health_viral_genomics/blob/main/tasks/task_assembly_metrics.wdl) currently uses container: `staphb/samtools:1.10`

I suggest we make a container that has samtools v1.12 and bwa v0.7.17-r1188 that all these tasks can pull from. Or we can use samtools v1.10 then still pull from `staphb/samtools:1.10` for `task_assembly_metrics.wdl` and then that workflow will have an easy way to see the version of samtools used.

**Comment by kapsakcj** [comment]
> I suggest we make a container that has samtools v1.12 and bwa v0.7.17-r1188 that all these tasks can pull from

and additionally ivar 1.3.1, right?

We could update the existing ivar 1.3.1 dockerfile to include bwa.

And for the `variant_call` task, I believe the reason it's currently stuck with that container due to it's use of the BED file & GFF file that are included, which the ivar 1.3.1 dockerfile does not have.

Perhaps we could create a new dockerfile that includes everything, and use that for `task_consensus_call.wdl`

'everything' means:
  * ivar 1.3.1
  * samtools 1.12
  * bwa v0.7.17-r1188
  * bed file that's used in `staphb/ivar:1.2.2_artic20200528`
  * gff file that's used in `staphb/ivar:1.2.2_artic20200528`

could call the docker image `staphb/ivar:1.3.1_artic20200528`

And that is assuming we want to keep the bed & gff files instead of having the user supply them as an input parameter. Either way there's a solution!

**Comment by jvhagey** [comment]
Per @kevinlibuit the bedfile that is in the `staphb/ivar:1.2.2_artic20200528` is [incorrect and leading to primers not being trimmed](https://github.com/StaPH-B/staphb_toolkit/issues/42). The issue was brought up on [slack](https://staph-b-dev.slack.com/archives/CUKR746QL/p1616163753003200).  @kevinlibuit also mentioned that Theiagen is moving toward having the genome and bed files not being part of containers, but rather are user input. This would allow the ivar container to be less SC2 specific. Thoughts on removing the bed file and gff file and having them as user input instead? @kapsakcj @k-florek

**Comment by kapsakcj** [comment]
New dockerfile added: https://github.com/StaPH-B/docker-builds/tree/master/ivar/1.3.1_Titan

Thanks for the pull request, Jill!

Docker image is available https://hub.docker.com/r/staphb/ivar/tags?page=1&ordering=last_updated

```
docker pull staphb/ivar:1.3.1-titan
```

Only other addition might be minimap2, but we can add that later if requested
